import uuid
from datetime import datetime

from sqlalchemy import DateTime, Float, ForeignKey, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import GUID, Base, TimestampMixin, UUIDPrimaryKeyMixin


class LogRecord(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """Synthetic application log line, generated by the incident simulator (Phase 4)."""

    __tablename__ = "logs"

    service_id: Mapped[uuid.UUID] = mapped_column(
        GUID(),
        ForeignKey("services.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    incident_id: Mapped[uuid.UUID | None] = mapped_column(
        GUID(),
        ForeignKey("incidents.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    occurred_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, index=True
    )
    level: Mapped[str] = mapped_column(String(20), nullable=False)
    message: Mapped[str] = mapped_column(Text(), nullable=False)
    trace_id: Mapped[str | None] = mapped_column(String(64), nullable=True, index=True)


class MetricRecord(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """Synthetic time-series metric point (e.g. error_rate, latency_ms, pool_utilization)."""

    __tablename__ = "metrics"

    service_id: Mapped[uuid.UUID] = mapped_column(
        GUID(),
        ForeignKey("services.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    incident_id: Mapped[uuid.UUID | None] = mapped_column(
        GUID(),
        ForeignKey("incidents.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    occurred_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, index=True
    )
    metric_name: Mapped[str] = mapped_column(String(100), nullable=False, index=True)
    value: Mapped[float] = mapped_column(Float(), nullable=False)
    unit: Mapped[str | None] = mapped_column(String(20), nullable=True)


class TraceRecord(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """Synthetic distributed trace span."""

    __tablename__ = "traces"

    service_id: Mapped[uuid.UUID] = mapped_column(
        GUID(),
        ForeignKey("services.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    incident_id: Mapped[uuid.UUID | None] = mapped_column(
        GUID(),
        ForeignKey("incidents.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    trace_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    span_name: Mapped[str] = mapped_column(String(200), nullable=False)
    started_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    duration_ms: Mapped[float] = mapped_column(Float(), nullable=False)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="ok")


class DeploymentEvent(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """Synthetic deployment history entry — used to correlate incidents with recent changes."""

    __tablename__ = "deployments"

    service_id: Mapped[uuid.UUID] = mapped_column(
        GUID(),
        ForeignKey("services.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    deployed_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, index=True
    )
    version: Mapped[str] = mapped_column(String(50), nullable=False)
    deployed_by: Mapped[str | None] = mapped_column(String(100), nullable=True)
    change_summary: Mapped[str | None] = mapped_column(Text(), nullable=True)
    is_rollback: Mapped[bool] = mapped_column(default=False, nullable=False)
